---
title: "Assignment_2"
output: html_document
date: "2024-05-16"
---

##Assignment. End-to-end data analysis in R

#Part 1

# Load tidyverse packages
```{r}
library("tidyverse")
library("sf") 
library("terra")
library("tmap")
```


#load data
```{r}
data <- read.csv("../data/export (2).csv")
```

```{r}
glimpse(data)
```
# Data wrangling

#change from character to numeric and removing "," in the numbers
```{r}
#data <- 
  data %>%
  mutate(CalendarYear = as.numeric(CalendarYear)) %>%
  mutate(Tonnes = str_replace(Tonnes, pattern = ",", replacement = "")) |>
  mutate(Tonnes = as.numeric(Tonnes))
#data
```


#Part 2

#Create a plot:
```{r}
ggplot(data, aes(CalendarYear, Tonnes)) +
  geom_point(aes(color = CalendarYear)) +
  geom_smooth()
 
```

```{r}
ggplot(data, aes(CalendarYear, Tonnes)) +
  geom_point(aes(color = CalendarYear), size = 2, alpha = 0.5) + # Adjust size and transparency
  geom_smooth(se = FALSE) +
  labs(
    title = "Fuel efficiency generally decreases with engine size",
    subtitle = "Two seaters (sports cars) are an exception because of their light weight",
    caption = "Data from fueleconomy.gov",
    x = "Calendar Year",  # Improve axis labels
    y = "Tonnes"
  ) +
  theme(axis.text = element_text(size = 10, angle = 45, hjust = 1))  # Adjust axis label size and orientation

```


```{r}
ggplot(data, aes(CalendarYear, Tonnes)) +
  geom_point(aes(color = CalendarYear)) +
  geom_smooth(se = FALSE) +
  labs(
    title = "Fuel efficiency generally decreases with engine size",
    subtitle = "Two seaters (sports cars) are an exception because of their light weight",
    caption = "Data from fueleconomy.gov",
    x = "Calendar Year",
    y = "Tonnes"
  ) +
  theme(
    axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)
  )



```

```{r}
ggplot(data, aes(CalendarYear, Tonnes)) +
  geom_point(aes(color = CalendarYear)) +
  geom_smooth(se = FALSE) +
  labs(
    title = "Fuel efficiency generally decreases with engine size",
    subtitle = "Two seaters (sports cars) are an exception because of their light weight",
    caption = "Data from fueleconomy.gov",
    x = "Calendar Year",
    y = "Tonnes"
  ) +
  theme(
    axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)
  ) +
  scale_y_continuous(breaks = seq(1000, 7000, by = 1000), labels = seq(1000, 7000, by = 1000))

```

